// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/read/read.d.ts
declare module 'read' {
	function Read(options: Read.Options, callback: (error: any, result: string, isDefault: boolean) => any): void;

	namespace Read {
		interface Options {
			prompt?: string;
			silent?: boolean;
			replace?: string;
			timeout?: number;
			default?: string;
			edit?: boolean;
			terminal?: boolean;
			input?: any;
			output?: any;
		}
	}

	export = Read;
}
